services:
  node:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - postgres
    env_file:
      - .env 
  postgres: 
    image: postgres:17-alpine3.21
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d 
    env_file:
      - .env
    environment:
      POSTGRES_NAME: ${DB_USER}
      POSTGRES_USER: ${DB_PASS}
      POSTGRES_PASSWORD: ${DB_PASS}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
volumes:
  data :

networks:
  node:
    
